core/accounts/urls.py
from django.urls import path, include

from . import views

app_name = "accounts"

urlpatterns = [
    # path("", include("django.contrib.auth.urls")),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("api/v1/", include("accounts.api.v1.urls")),
    # path('send-email/', views.send_email, name='send-email'),
    path('test/', views.test_postman, name='test-postman'),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Task API",
        default_version="v1",
        description="The description of ToDo CBV project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="poorya189@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
    path('api/v1/weather/', include('weather.urls')),
    path("api-docs/", include_docs_urls(title="api sample")),
    path("swagger/output.json", schema_view.without_ui(cache_timeout=0), name="schema-json",),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui",),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]


# when DEBUG is True, serve media & static files for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/tasks/api/v1/urls.py
from django.urls import path

# from .views import api_task_list_view
from . import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("task", views.TaskModelViewSet, basename="task")
urlpatterns = router.urls

urlpatterns += [
    path("lists/", views.TasksListApiView.as_view({'get': 'list'}), name="lists"),
    path("task/update/<int:pk>/", views.TasksListUpdateApiView.as_view(), name="task-update"),
    # path('task/', views.api_task_list_view,name='api-task-list'),
    # path('task/', views.TaskList, name='task-list'),
    # path('task/', views.TaskList.as_view(), name='task-list'),
    # path('task/<int:id>/', views.taskDetail, name='task-detail'),
    # path('task/<int:pk>/', views.TaskDetail.as_view(), name='task-detail'),
    # path('task/', views.TaskViewSet.as_view({'get':'list','post':'create'}), name='task-list'),
    # path('task/<int:pk>/', views.TaskViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), name='task-list'),
]

core/tasks/urls.py
from django.urls import path, include
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.TasksListView.as_view(), name="list_view"),
    path("api/", views.TasksListApiView.as_view(), name="list_view_api"),
    path("create/", views.TaskCreateView.as_view(), name="task-create"),
    path("edit/<int:pk>/", views.TaskUpdateView.as_view(), name="task-update"),
    path("delete/<int:pk>/", views.TaskDeleteView.as_view(), name="task-delete"),
    path("complete/<int:pk>/", views.TaskCompleteView.as_view(), name="task-complete"),
    path("api/v1/", include("tasks.api.v1.urls")),
    # test
    # path('', views.IndexView.as_view(), name='index'),
]

core/tasks/models.py
from django.db import models

# from django.conf import settings
# from django.contrib.auth import get_user_model

# from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

# User = get_user_model()


class Task(models.Model):
    creator = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    complete = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateTimeField(null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.title[0:4]

    def get_absolute_api_url(self, **kwargs):
        return reverse("tasks:api-v1:task-detail", kwargs={"pk": self.pk})
        # return f"/api/v1/task/{self.id}/"

    class Meta:
        order_with_respect_to = "creator"

core/tasks/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "complete", "active", "due_date"]

core/tasks/api/v1/views.py
# API
"""
from django.http import HttpResponse
def api_task_list_view(request):
    return HttpResponse("ok")
"""

# API function base view
# from rest_framework import mixins,status
from rest_framework import viewsets

# from rest_framework.decorators import api_view, permission_classes
from rest_framework.filters import SearchFilter, OrderingFilter

# from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated

# from rest_framework.response import Response
# from rest_framework.views import APIView
from django_filters.rest_framework import DjangoFilterBackend

from django.shortcuts import get_object_or_404


from .serializers import TaskSerializer
from .permissions import IsOwnerOrReadOnly
from .paginations import CustomPagination
from .filter import TaskFilter
from ...models import Task


"""
# @api_view('GET',)
# @api_view(['GET','POST'])
@api_view()
def api_task_list_view(request):
    return Response({'name':'poorya'})

"""


"""
@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
def TaskList(request):
    if request.method == 'GET':
        tasks = Task.objects.all()
        # tasks = Task.objects.filter(complete=False)
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = TaskSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
        # if serializer.is_valid():
        #     serializer.save()
        #     return Response(serializer.data)
        # else:
        #     return Response(serializer.errors)
"""


"""
class TaskList(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = TaskSerializer
    def get(self,request):
        tasks = Task.objects.all()
        # tasks = Task.objects.filter(complete=False)
        serializer = TaskSerializer(tasks, many=True)
        return Response(serializer.data)
    def post(self,request):
        serializer = TaskSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
"""


"""
class TaskList(ListCreateAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = TaskSerializer
    queryset = Task.objects.all() #Task.objects.filter(complete=False)
"""

"""
@api_view(['GET','PUT','DELETE'])
@permission_classes([IsAuthenticated])
def taskDetail(request,id):
    task = get_object_or_404(Task,pk=id)
    if request.method == 'GET':
        serializer = TaskSerializer(task)
        return Response(serializer.data)
        # try:
        #     task = Task.objects.get(pk=id)
        #     serializer = TaskSerializer(task)
        #     return Response(serializer.data)
        # except Task.DoesNotExist:
        #     return Response({'detail':'task does not found'},status=status.HTTP_404_NOT_FOUND)
    elif request.method == 'PUT':
        serializer = TaskSerializer(task,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    elif request.method == 'DELETE':
        task.delete()
        return Response({'detail':'item removed successfuly.'},status=status.HTTP_204_NO_CONTENT)
"""


"""
class TaskDetail(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = TaskSerializer
    def get(self,request,id):
        task = get_object_or_404(Task,pk=id)
        serializer = self.serializer_class(task)
        return Response(serializer.data)
    def put(self,request,id):
        task = get_object_or_404(Task,pk=id)
        serializer = TaskSerializer(task,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    def delete(self,request,id):
        task = get_object_or_404(Task,pk=id)
        task.delete()
        return Response({'detail':'item removed successfuly.'},status=status.HTTP_204_NO_CONTENT)
"""

"""'
class TaskDetail(RetrieveUpdateDestroyAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = TaskSerializer
    queryset = Task.objects.all()
"""

# Example for ViewSet in CBV

from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic.base import TemplateView

class TaskModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = TaskSerializer
    #queryset = Task.objects.all()  # Task.objects.filter(complete=False)
    def get_queryset(self):
        return Task.objects.filter(creator__user=self.request.user)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_class = TaskFilter
    ordering_fields = ["created_date", "due_date"]
    # filterset_fields = ['creator', 'title', 'complete', 'active']
    search_fields = ["title"]
    pagination_class = CustomPagination
    def perform_update(self, serializer):
        serializer.save()


class ActiveUserRequiredMixin(UserPassesTestMixin):
    def test_func(self, *args, **kwargs):
        return self.request.user.is_active


"""
class TasksListApiView(ActiveUserRequiredMixin, TemplateView):
    permission_classes = [IsOwnerOrReadOnly]
    template_name = 'tasks/new_task_list.html'
    # template_name = 'tasks/task_list_api.html'
"""

    
    
class TasksListApiView(viewsets.ModelViewSet, TemplateView):
    # permission_classes = [IsOwnerOrReadOnly]
    template_name = 'tasks/new_task_list.html'
    # template_name = 'tasks/task_list_api.html'
    serializer_class = TaskSerializer
    #queryset = Task.objects.all()  # Task.objects.filter(complete=False)
    def get_queryset(self):
        return Task.objects.filter(creator__user=self.request.user)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_class = TaskFilter
    ordering_fields = ["created_date", "due_date"]
    # filterset_fields = ['creator', 'title', 'complete', 'active']
    search_fields = ["title"]
    pagination_class = CustomPagination
    def perform_update(self, serializer):
        serializer.save()    
    
    

class TasksListUpdateApiView(ActiveUserRequiredMixin, TemplateView):
    template_name = 'tasks/task_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_id = self.kwargs.get('pk')
        context['task'] = get_object_or_404(Task, id=task_id, creator__user=self.request.user)
        return context

core/tasks/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import View
from django.views.generic.base import TemplateView
from django.http import JsonResponse
import json

from accounts.models import Profile
from .models import Task
from weather.views import WeatherView


"""
class TaskListView(TemplateView):
    template_name = 'tasks/task_list3.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.all()
        context['author'] = Task.objects.first().user
        return context
"""

"""
class TListView(ListView):
    # model = Task
    queryset = Task.objects.all()
    template_name = 'tasks/task_list3.html'
    context_object_name = 'tasks'
    paginate_by = 6
    
    def get_queryset(self):
        return Task.objects.all()
        # return Task.objects.filter(complete=Flase)
        # return Task.objects.filter(active=True)
"""


class ActiveUserRequiredMixin(UserPassesTestMixin):
    def test_func(self, *args, **kwargs):
        return self.request.user.is_active


class TasksListView(ActiveUserRequiredMixin, ListView):
# class TasksListView(ListView):
    model = Task
    template_name = "tasks/task_list3.html"
    context_object_name = "tasks"
    paginate_by = 6

    def get_queryset(self):
        # queryset = Task.objects.all()
        profile_instance = get_object_or_404(Profile, user=self.request.user)
        # queryset = Task.objects.filter(user=self.request.user)
        queryset = Task.objects.filter(creator=profile_instance)
        filter_value = self.request.GET.get("filter")
        sort_value = self.request.GET.get("sort")
        # filter_value = self.request.GET.get('filter')
        # sort_value = self.request.GET.get('sort')
        if filter_value == "1":
            queryset = queryset.filter(title__isnull=False)
        elif filter_value == "2":
            queryset = queryset.filter(complete=True)
        elif filter_value == "3":
            queryset = queryset.filter(active=True)
        elif filter_value == "4":
            queryset = queryset.filter(due_date__isnull=False)

        if sort_value == "2":
            queryset = queryset.order_by("due_date")
        else:
            queryset = queryset.order_by("-created_date")

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        

        request = self.request
        weather_view = WeatherView.as_view()
        response = weather_view(request)
        
        if isinstance(response, JsonResponse):
            # Decode the JSON response
            weather_data = response.content.decode('utf-8')
            # Parse it to a Python dict
            context['weather_data'] = json.loads(weather_data)
        else:
            context['weather_data'] = {'error': 'Unable to fetch weather data.'}

        return context
    
    
    
    
class TasksListApiView(ActiveUserRequiredMixin, TemplateView):
    template_name = 'tasks/task_list_api.html'
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['tasks'] = Task.objects.all()
    #     return context


class TaskCreateView(LoginRequiredMixin, CreateView):
# class TaskCreateView( CreateView):
    model = Task
    template_name = "tasks/task_list3.html"
    fields = ["title", "due_date"]
    success_url = "/"

    def form_valid(self, form):
        profile_instance = get_object_or_404(Profile, user=self.request.user)
        form.instance.creator = profile_instance
        # form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
# class TaskUpdateView(UpdateView):
    model = Task
    template_name = "tasks/task_detail.html"
    fields = ["title", "due_date"]
    context_object_name = "task"
    # form_class = TaskForm i didnt create TaskForm
    success_url = "/"

    def form_valid(self, form):
        profile_instance = get_object_or_404(Profile, user=self.request.user)
        form.instance.creator = profile_instance
        # form.instance.user = self.request.user
        return super().form_valid(form)


class TaskCompleteView(LoginRequiredMixin, View):
# class TaskCompleteView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.complete = not task.complete
        task.active = not task.active
        task.save()
        return redirect("tasks:list_view")


class TaskDeleteView(DeleteView):
    model = Task
    context_object_name = "task"
    success_url = "/"

core/templates/tasks/task_form.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

core/templates/tasks/task_list3.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Task</title>
  <link rel="stylesheet" href="staticfiles/main.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"></script>  
</head>
<body>
    
  <section class="vh-100">
    <div class="weather" style="position: absolute; top: 20px; left: 20px; z-index: 1000; background-color: rgba(255, 255, 255, 0.8); padding: 10px; border-radius: 5px;">
      {% if weather_data.weather %}
          <h2 style="font-size: 1.2em; margin: 0;">Weather in {{ weather_data.name }}</h2>
          <div style="display: flex; align-items: center;">          
            <img style="width: 50px; margin-right:10px;" src="http://openweathermap.org/img/wn/{{ weather_data.weather.0.icon }}@2x.png" alt="Weather Icon">
          </div>
            <p class="weather-info" style="margin:0;"><strong>Condition:</strong> {{ weather_data.weather.0.description }}</p>
          <p class="weather-info" style="margin:0;"><strong>Temperature:</strong> {{ weather_data.main.temp }} °C</p>

          <button id="show-button-{{ weather_data.id }}" style="display:inline; margin: 0 10px; cursor: pointer;" onclick="showDetails('{{ weather_data.id }}')">More details...</button>
      
      
          
          <div id="weather-details-{{ weather_data.id }}" style="display: none;">
              <p style="margin:0;" class="weather-info"><strong>Feels Like:</strong> {{ weather_data.main.feels_like }} °C</p>
              <p style="margin:0;" class="weather-info"><strong>Humidity:</strong> {{ weather_data.main.humidity }}%</p>
              <p style="margin:0;" class="weather-info"><strong>Pressure:</strong> {{ weather_data.main.pressure }} hPa</p>
              <p style="margin:0;" class="weather-info"><strong>Wind Speed:</strong> {{ weather_data.wind.speed }} m/s</p>
              <p style="margin:0;" class="weather-info"><strong>Wind Direction:</strong> {{ weather_data.wind.deg }}°</p>
              <p style="margin:0;" class="weather-info"><strong>Cloudiness:</strong> {{ weather_data.clouds.all }}%</p>
              {% if weather_data.rain %}
                  <p style="margin:0;" class="weather-info"><strong>Rain (last hour):</strong> {{ weather_data.rain.1h }} mm</p>
              {% endif %}
              <p style="margin:0;" class="weather-info"><strong>Sunrise:</strong> {{ weather_data.sys.sunrise  }}</p>
              <p style="margin:0;" class="weather-info"><strong>Sunset:</strong> {{ weather_data.sys.sunset }}</p>
          
              <button id="hide-button-{{ weather_data.id }}" style="display:none; margin: 0 10px; cursor: pointer;" onclick="hideDetails('{{ weather_data.id }}')">Hide Details</button>

          </div>
      {% else %}
          <p>No weather data available.</p>
      {% endif %}
  </div>
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card" id="list1" style="border-radius: .75rem; background-color: #eff1f2;">
            <div class="card-body py-4 px-4 px-md-5">
  
              <p class="h1 text-center mt-3 mb-4 pb-3 text-primary">
                <i class="fas fa-check-square me-1"></i>
                {% if tasks %}
                <u>My Todo-s : {{ tasks.0.creator.first_name }} {{ tasks.0.creator.last_name }} </u>
                {% else %}
                <u>My Todo-s</u>
                {% endif %}
                <a href="{% url 'accounts:logout' %}" class="text-danger" data-mdb-tooltip-init title="Logout"><i class="fas fa-sign-out-alt ms-3"></i></a>
              </p>
  
              <div class="pb-2">
                <div class="card">
                  <div class="card-body">
                    <div class="flex-row align-items-center">                      
                      <form class="pt-3" method="POST" action="{% url 'tasks:task-create' %}">
                          {% csrf_token %}
                          <div class="input-group mb-3">
                            <input type="text" class="form-control rounded-4 me-3" name="title" placeholder="Enter task title" aria-label="Recipient's username" aria-describedby="button-addon2">
                            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary rounded-4" >Add</button>
                          </div>
                          <div class="d-flex justify-content-center align-items-center mb-4 pt-2 pb-3">
                            <span class="me-3">change due date:</span> 
                            <input value="{{ task.due_date|date:'Y-m-d\TH:i' }}" name="due_date" type="datetime-local" class="form-control me-3" id="dueDateTime" style="width: 40ch;">
                            <i class="fas fa-calendar-alt fa-lg me-3"></i>
                        </div>
                        </form>
                    </div>
                  </div>
                </div>
              </div>
  
              <hr class="my-4">
  

            <form method="get">
              <div class="d-flex justify-content-end align-items-center mb-4 pt-2 pb-3">
                  <p class="small mb-0 me-2 text-muted">Filter</p>
                  <select name="filter" onchange="this.form.submit()">
                      <option value="1" {% if request.GET.filter == '1' %}selected{% endif %}>All</option>
                      <option value="2" {% if request.GET.filter == '2' %}selected{% endif %}>Completed</option>
                      <option value="3" {% if request.GET.filter == '3' %}selected{% endif %}>Active</option>
                      <option value="4" {% if request.GET.filter == '4' %}selected{% endif %}>Has due date</option>
                  </select>
                  <p class="small mb-0 ms-4 me-2 text-muted">Sort</p>
                  <select name="sort" onchange="this.form.submit()">
                      <option value="1" {% if request.GET.sort == '1' %}selected{% endif %}>Added date</option>
                      <option value="2" {% if request.GET.sort == '2' %}selected{% endif %}>Due date</option>
                  </select>
                  <a href="#!" style="color: #23af89;" data-mdb-tooltip-init title="Ascending"><i class="fas fa-sort-amount-down-alt ms-2"></i></a>
              </div>
          </form>

          {% for task in tasks %}
          <ul class="list-group list-group-horizontal rounded-0">
              <li class="list-group-item d-flex align-items-center ps-0 pe-3 py-1 rounded-0 border-0 bg-transparent">
                  <div class="form-check">
                      <form method="POST" action="{% url 'tasks:task-complete' pk=task.id %}" id="update-form-{{ task.id }}">
                          {% csrf_token %}
                          <input type="hidden" name="complete" value="{% if task.complete %}False{% else %}True{% endif %}">
                          {% if task.complete %}
                              <input class="form-check-input me-0" type="checkbox" value="" id="flexCheckChecked1" aria-label="..." checked onchange="submitForm(this, '{{ task.id }}')" />
                          {% else %}
                              <input class="form-check-input me-0" name="complete" type="checkbox" value="" id="flexCheckChecked2" aria-label="..." onchange="submitForm(this, '{{ task.id }}')" />
                          {% endif %}
                      </form>
                  </div>
              </li>
              <li class="list-group-item px-3 py-1 d-flex align-items-center flex-grow-1 border-0 bg-transparent">
                  <style>.completed {text-decoration: line-through;}</style>
                  <p class="lead fw-normal mb-0 task-title {% if task.complete %}completed{% endif %}" id="task-title-{{ task.id }}">{{ task.title }}</p>                
              </li>
      
              {% if task.due_date %}
                  <li class="list-group-item px-3 py-1 d-flex align-items-center border-0 bg-transparent">
                      <div class="py-2 px-3 me-2 border border-warning rounded-3 d-flex align-items-center bg-body-tertiary">
                          <p class="small mb-0">
                              <a href="#!" data-mdb-tooltip-init title="Due on date"><i class="fas fa-hourglass-half me-2 text-warning"></i></a>
                              {{ task.due_date }}
                          </p>
                      </div>
                  </li>
              {% endif %}
              <li class="list-group-item ps-3 pe-0 py-1 rounded-0 border-0 bg-transparent">
                  <div class="d-flex flex-row justify-content-end mb-1">
                      <a href="{% url 'tasks:task-update' pk=task.id %}" class="text-info" data-mdb-tooltip-init title="Edit todo"><i class="fas fa-pencil-alt me-3"></i></a>
                      <a type="button" href="{% url 'tasks:task-delete' pk=task.id %}" class="text-danger" data-mdb-tooltip-init title="Delete todo"><i class="fas fa-trash-alt"></i></a>
                    </div>
                        <div class="text-end text-muted">
                            <a href="#!" class="text-muted" data-mdb-tooltip-init title="Created date">
                                <p class="small mb-0"><i class="fas fa-info-circle me-2"></i>{{ task.created_date}}</p>
                            </a>                    
                        </div>
              </li>
          </ul>
      {% endfor %}



                  
                  <div class="row">
                    <div class="col-md-12">
                        <nav aria-label="Page navigation">
                            <ul class="pagination justify-content-center">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                                            <span aria-hidden="true">
                                                <span class="lnr lnr-chevron-left"></span>
                                            </span>
                                        Prev</a>
                                    </li>
                                {% endif %}
                
                                {% for i in page_obj.paginator.page_range %}
                                    {% if page_obj.number == i %}																			
                                        <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                                    {% else %}
                                        <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                                    {% endif %}
                                {% endfor %}		                            
                                    
                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                            <span aria-hidden="true">
                                                <span class="lnr lnr-chevron-right"></span>
                                            </span>
                                        Next</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div><!-- end col -->
                </div><!-- end row -->


            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script>
    function toggleStrike(checkbox, taskId) {
        const titleElement = document.getElementById('task-title-' + taskId);
        if (checkbox.checked) {
            titleElement.style.textDecoration = 'line-through';
        } else {
            titleElement.style.textDecoration = 'none';
        }
    }
</script>
<script>
  function submitForm(checkbox, taskId) {
      const form = document.getElementById('update-form-' + taskId);
      form.elements['complete'].value = checkbox.checked ? 'True' : 'False';
      form.submit();
  }
</script>


<script>
  function showDetails(id) {
      const details = document.getElementById(`weather-details-${id}`);
      const showButton = document.getElementById(`show-button-${id}`);
      const hideButton = document.getElementById(`hide-button-${id}`);

      details.style.display = "block";
      showButton.style.display = "none";
      hideButton.style.display = "inline";
  }

  function hideDetails(id) {
      const details = document.getElementById(`weather-details-${id}`);
      const showButton = document.getElementById(`show-button-${id}`);
      const hideButton = document.getElementById(`hide-button-${id}`);

      details.style.display = "none";
      showButton.style.display = "inline"; 
      hideButton.style.display = "none"; 
  }
</script>


</body>
</html>